# Generated by Django 4.1.6 on 2023-02-15 18:26

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категорія користувача')),
                ('address', models.CharField(max_length=150, verbose_name='Адреса розташування')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('сл.', 'службовець'), ('солд.', 'солдат'), ('ст.солд.', 'старший солдат'), ('мол.с-нт', 'Молодший сержант'), ('с-нт', 'Сержант'), ('ст.с-нт', 'Старший сержант'), ('гол.с-нт', 'Головний сержант'), ('шт.с-нт', 'Штаб-сержант'), ('м.с-нт', 'Майстер-сержант'), ('ст.м.с-нт', 'Старший майстер-сержант'), ('гол.м.с-нт', 'Головний майстер-сержант'), ('мол.л-нт', 'Молодший лейтенант'), ('л-нт', 'Лейтенант'), ('ст.л-нт', 'Старший лейтенант'), ('к-н', 'Капітан'), ('м-р', 'Майор'), ('п/п-к', 'Підполковник'), ('п-к', 'Полковник'), ('бриг.ген.', 'Бригадний генерал'), ('ген.м-р', 'Генерал-майор'), ('ген.л-нт', 'Генерал-лейтенант'), ('ген.', 'Генерал')], max_length=30, verbose_name='Звання')),
                ('firstname', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('lastname', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('surname', models.CharField(blank=True, max_length=25, null=True, verbose_name='По батькові')),
                ('position', models.CharField(max_length=100, verbose_name='посада')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Додатковий коментар')),
                ('officialPhone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Службовий номер телефону')),
                ('personalPhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('categoryId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employees.category', verbose_name='Категорія користувача')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
            },
        ),
    ]
