# Generated by Django 4.1.6 on 2023-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_categoryid_employee_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/employee/%Y/%m/%d', verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(choices=[('сл.', 'Службовець'), ('солд.', 'Солдат'), ('ст.солд.', 'Старший солдат'), ('мол.с-нт', 'Молодший сержант'), ('с-нт', 'Сержант'), ('ст.с-нт', 'Старший сержант'), ('гол.с-нт', 'Головний сержант'), ('шт.с-нт', 'Штаб-сержант'), ('м.с-нт', 'Майстер-сержант'), ('ст.м.с-нт', 'Старший майстер-сержант'), ('гол.м.с-нт', 'Головний майстер-сержант'), ('мол.л-нт', 'Молодший лейтенант'), ('л-нт', 'Лейтенант'), ('ст.л-нт', 'Старший лейтенант'), ('к-н', 'Капітан'), ('м-р', 'Майор'), ('п/п-к', 'Підполковник'), ('п-к', 'Полковник'), ('бриг.ген.', 'Бригадний генерал'), ('ген.м-р', 'Генерал-майор'), ('ген.л-нт', 'Генерал-лейтенант'), ('ген.', 'Генерал')], max_length=30, verbose_name='Звання'),
        ),
    ]
