# Generated by Django 4.1.6 on 2023-03-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_historicalemployee_historicalcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Локація', 'verbose_name_plural': 'Локації'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Локація', 'verbose_name_plural': 'historical Локації'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Локація користувача'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='employees.category', verbose_name='Локація користувача'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Локація користувача'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.category', verbose_name='Локація користувача'),
        ),
    ]
