# Generated by Django 4.1.6 on 2023-03-05 12:44

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to=employees.models.Employee.directory_path, verbose_name='Фотографія'),
        ),
        migrations.DeleteModel(
            name='HistoricalEmployee',
        ),
    ]
