# Generated by Django 4.1.6 on 2023-03-09 14:58

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_photo_delete_historicalemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employees.models.Employee.directory_path, verbose_name='Фотографія'),
        ),
    ]
