# Generated by Django 4.1.6 on 2023-03-12 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0007_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rank', models.CharField(choices=[('сл.', 'Службовець'), ('солд.', 'Солдат'), ('ст.солд.', 'Старший солдат'), ('мол.с-нт', 'Молодший сержант'), ('с-нт', 'Сержант'), ('ст.с-нт', 'Старший сержант'), ('гол.с-нт', 'Головний сержант'), ('шт.с-нт', 'Штаб-сержант'), ('м.с-нт', 'Майстер-сержант'), ('ст.м.с-нт', 'Старший майстер-сержант'), ('гол.м.с-нт', 'Головний майстер-сержант'), ('мол.л-нт', 'Молодший лейтенант'), ('л-нт', 'Лейтенант'), ('ст.л-нт', 'Старший лейтенант'), ('к-н', 'Капітан'), ('м-р', 'Майор'), ('п/п-к', 'Підполковник'), ('п-к', 'Полковник'), ('бриг.ген.', 'Бригадний генерал'), ('ген.м-р', 'Генерал-майор'), ('ген.л-нт', 'Генерал-лейтенант'), ('ген.', 'Генерал')], max_length=30, verbose_name='Звання')),
                ('firstname', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('lastname', models.CharField(max_length=25, verbose_name='Прізвище')),
                ('surname', models.CharField(blank=True, max_length=25, null=True, verbose_name='По батькові')),
                ('position', models.CharField(max_length=100, verbose_name='посада')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Додатковий коментар')),
                ('officialPhone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Службовий номер телефону')),
                ('personalPhone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region=None)),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Фотографія')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.category', verbose_name='Локація користувача')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Співробітник',
                'verbose_name_plural': 'historical Співробітники',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
