# Generated by Django 4.1.6 on 2023-02-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус обладнання')),
            ],
            options={
                'verbose_name': 'Статус обладнання',
                'verbose_name_plural': 'Статуси обладнання',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія обладнання', 'verbose_name_plural': 'Категорії обладнання'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Обладнання', 'verbose_name_plural': 'Обладнання'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Категорія обладнання'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='statusId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.status', verbose_name='Статус'),
        ),
    ]
