# Generated by Django 4.1.6 on 2023-02-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_categoryid_employee_category'),
        ('equipment', '0004_rename_categoryid_equipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Відповідальний'),
        ),
    ]
