# Generated by Django 4.1.6 on 2023-02-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo_alter_employee_rank'),
        ('nguhub', '0001_initial'),
        ('equipment', '0005_equipment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nguhub.location', verbose_name='Місце закріплення'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_employee', to='employees.employee', verbose_name='Користувач'),
        ),
    ]
