# Generated by Django 4.1.6 on 2023-02-27 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_photo_alter_employee_rank'),
        ('equipment', '0008_equipment_employee_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_responsible', to='employees.employee', verbose_name='Матеріально Відповідальний'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='responsible_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Підстава закріплення матеріально відповідального'),
        ),
    ]
