# Generated by Django 4.1.6 on 2023-03-01 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_historicalstatus_historicalequipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='operationDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата введення в експлуатацію'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='operationDate',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата введення в експлуатацію'),
        ),
    ]
