# Generated by Django 4.1.6 on 2023-03-05 12:44

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_alter_equipment_operationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='status',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, upload_to=equipment.models.Equipment.directory_path, verbose_name='Фотографія'),
        ),
    ]
