# Generated by Django 4.1.6 on 2023-03-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_category_notes_historicalcategory_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Назва техніки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Назва техніки'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Серійний номер'),
        ),
    ]
