# Generated by Django 4.1.6 on 2023-03-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_photo_delete_historicalemployee'),
        ('equipment', '0017_alter_equipment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='inventoryNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='value',
            field=models.CharField(default='1', max_length=50, verbose_name='Кількість'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='inventoryNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='unit',
            field=models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='value',
            field=models.CharField(default='1', max_length=50, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='employee_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fixed_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Назва техніки'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_responsible', to='employees.employee', verbose_name='Матеріально відповідальний'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='responsible_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='employee_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='fixed_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Назва техніки'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='responsible',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Матеріально відповідальний'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='responsible_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер'),
        ),
    ]
