# Generated by Django 4.1.6 on 2023-03-09 14:58

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_equipment_cost_equipment_inventorynumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=equipment.models.Equipment.directory_path, verbose_name='Фотографія'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='photo',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Фотографія'),
        ),
    ]
