# Generated by Django 4.1.6 on 2023-03-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguhub', '0004_currentlocation_alter_historicallocation_options_and_more'),
        ('equipment', '0020_category_delete_reason_equipment_delete_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='currentLocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nguhub.currentlocation', verbose_name='Поточне місцезнаходження'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='currentLocation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nguhub.currentlocation', verbose_name='Поточне місцезнаходження'),
        ),
    ]
