# Generated by Django 4.1.6 on 2023-03-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0021_equipment_currentlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='destinationEquipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Додано до обладнання'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='destinationEquipment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipment', verbose_name='Додано до обладнання'),
        ),
    ]
