# Generated by Django 4.1.6 on 2023-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_equipment_destinationequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipmentType',
            field=models.IntegerField(choices=[(1, 'Обладнання'), (2, 'Елемент обладнання')], default=1, verbose_name='Тип обладнання'),
        ),
        migrations.AddField(
            model_name='historicalequipment',
            name='equipmentType',
            field=models.IntegerField(choices=[(1, 'Обладнання'), (2, 'Елемент обладнання')], default=1, verbose_name='Тип обладнання'),
        ),
    ]
