# Generated by Django 4.1.6 on 2023-03-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0023_equipment_equipmenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='destinationEquipment',
            field=models.ForeignKey(blank=True, limit_choices_to={'equipmentType': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Додано до обладнання'),
        ),
        migrations.AlterField(
            model_name='historicalequipment',
            name='destinationEquipment',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'equipmentType': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.equipment', verbose_name='Додано до обладнання'),
        ),
    ]
