# Generated by Django 4.1.6 on 2023-03-20 14:19

import datetime
import departmentEquipment.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0009_category_delete_reason_employee_delete_reason_and_more'),
        ('nguhub', '0004_currentlocation_alter_historicallocation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категорія обладнання')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
            ],
            options={
                'verbose_name': 'Категорія обладнання по службам',
                'verbose_name_plural': 'Категорії обладнання по службам',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Назва обладнання')),
                ('value', models.CharField(default='1', max_length=50, verbose_name='Кількість')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість')),
                ('serialNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер')),
                ('internalNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер')),
                ('inventoryNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=departmentEquipment.models.Equipment.directory_path, verbose_name='Фотографія')),
                ('operationDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата введення в експлуатацію')),
                ('responsible_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального')),
                ('fixed_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального')),
                ('employee_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача')),
                ('comment', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Додатковий коментар')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
                ('equipmentType', models.IntegerField(choices=[(1, 'Обладнання'), (2, 'Елемент обладнання')], default=1, verbose_name='Тип обладнання')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departmentEquipment.category', verbose_name='Категорія')),
                ('currentLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_equipment_currentLocation', to='nguhub.currentlocation', verbose_name='Поточне місцезнаходження')),
                ('destinationEquipment', models.ForeignKey(blank=True, limit_choices_to={'equipmentType': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='departmentEquipment.equipment', verbose_name='Додано до обладнання')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_equipment_employee', to='employees.employee', verbose_name='Користувач')),
                ('fixed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_equipment_fixed', to='employees.employee', verbose_name='За ким закріплено')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='department_equipment_location', to='nguhub.location', verbose_name='Місце закріплення')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_equipment_responsible', to='employees.employee', verbose_name='Матеріально відповідальний')),
            ],
            options={
                'verbose_name': 'Обладнання по службам',
                'verbose_name_plural': 'Обладнання по службам',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус обладнання')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
            ],
            options={
                'verbose_name': 'Статус обладнання',
                'verbose_name_plural': 'Статуси обладнання',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус обладнання')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Статус обладнання',
                'verbose_name_plural': 'historical Статуси обладнання',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=2048, verbose_name='Назва обладнання')),
                ('value', models.CharField(default='1', max_length=50, verbose_name='Кількість')),
                ('unit', models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість')),
                ('serialNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер')),
                ('internalNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер')),
                ('inventoryNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Фотографія')),
                ('operationDate', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата введення в експлуатацію')),
                ('responsible_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального')),
                ('fixed_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального')),
                ('employee_reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача')),
                ('comment', models.CharField(blank=True, max_length=2048, null=True, verbose_name='Додатковий коментар')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
                ('equipmentType', models.IntegerField(choices=[(1, 'Обладнання'), (2, 'Елемент обладнання')], default=1, verbose_name='Тип обладнання')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departmentEquipment.category', verbose_name='Категорія')),
                ('currentLocation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nguhub.currentlocation', verbose_name='Поточне місцезнаходження')),
                ('destinationEquipment', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'equipmentType': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departmentEquipment.equipment', verbose_name='Додано до обладнання')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Користувач')),
                ('fixed', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='За ким закріплено')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nguhub.location', verbose_name='Місце закріплення')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='Матеріально відповідальний')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='departmentEquipment.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'historical Обладнання по службам',
                'verbose_name_plural': 'historical Обладнання по службам',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категорія обладнання')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі')),
                ('delete_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Категорія обладнання по службам',
                'verbose_name_plural': 'historical Категорії обладнання по службам',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departmentEquipment.status', verbose_name='Статус'),
        ),
    ]
