# Generated by Django 4.1.6 on 2023-07-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('notes', models.CharField(max_length=255, verbose_name='Додаткові відомості')),
            ],
            options={
                'verbose_name': 'Бойовий пост',
                'verbose_name_plural': 'Бойові пости',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='is_operator',
            field=models.BooleanField(default=True, null=True, verbose_name="Зв'язківець"),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='is_operator',
            field=models.BooleanField(default=True, null=True, verbose_name="Зв'язківець"),
        ),
        migrations.AddField(
            model_name='employee',
            name='actionPost',
            field=models.ManyToManyField(to='employee.actionpost', verbose_name='Бойовий пост'),
        ),
    ]
