# Generated by Django 4.1.6 on 2023-07-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_actionpost_employee_is_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('day1', models.BooleanField(default=False)),
                ('day2', models.BooleanField(default=False)),
                ('day3', models.BooleanField(default=False)),
                ('day4', models.BooleanField(default=False)),
                ('day5', models.BooleanField(default=False)),
                ('day6', models.BooleanField(default=False)),
                ('day7', models.BooleanField(default=False)),
                ('day8', models.BooleanField(default=False)),
                ('day9', models.BooleanField(default=False)),
                ('day10', models.BooleanField(default=False)),
                ('day11', models.BooleanField(default=False)),
                ('day12', models.BooleanField(default=False)),
                ('day13', models.BooleanField(default=False)),
                ('day14', models.BooleanField(default=False)),
                ('day15', models.BooleanField(default=False)),
                ('day16', models.BooleanField(default=False)),
                ('day17', models.BooleanField(default=False)),
                ('day18', models.BooleanField(default=False)),
                ('day19', models.BooleanField(default=False)),
                ('day20', models.BooleanField(default=False)),
                ('day21', models.BooleanField(default=False)),
                ('day22', models.BooleanField(default=False)),
                ('day23', models.BooleanField(default=False)),
                ('day24', models.BooleanField(default=False)),
                ('day25', models.BooleanField(default=False)),
                ('day26', models.BooleanField(default=False)),
                ('day27', models.BooleanField(default=False)),
                ('day28', models.BooleanField(default=False)),
                ('day29', models.BooleanField(default=False)),
                ('day30', models.BooleanField(default=False)),
                ('day31', models.BooleanField(default=False)),
                ('actionPost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.actionpost', verbose_name='Бойовий пост')),
                ('employee', models.ForeignKey(limit_choices_to={'is_operator': True}, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Черговий')),
            ],
            options={
                'verbose_name': 'Журнал чергувань',
                'verbose_name_plural': 'Журнали чергувань',
            },
        ),
    ]
