# Generated by Django 4.1.6 on 2023-07-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nguhub.location', verbose_name='Локація'),
        ),
    ]
