# Generated by Django 4.1.6 on 2023-03-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguhub', '0002_historicallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення'),
        ),
        migrations.AddField(
            model_name='location',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Причина видалення'),
        ),
    ]
