# Generated by Django 4.1.6 on 2023-02-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='categoryId',
            new_name='category',
        ),
    ]
