# Generated by Django 4.1.6 on 2023-02-19 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_employee'),
        ('elements', '0002_rename_categoryid_element_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='equipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='equipment.equipment', verbose_name='Встановлено на обладнання'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Категорія'),
        ),
    ]
