# Generated by Django 4.1.6 on 2023-02-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_employee'),
        ('elements', '0004_alter_category_options_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.equipment', verbose_name='Встановлено на обладнання'),
        ),
    ]
