# Generated by Django 4.1.6 on 2023-02-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipment_employee'),
        ('elements', '0005_alter_element_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='value',
            field=models.CharField(default='Н/Д', max_length=20, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='element',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='equipment.equipment', verbose_name='Встановлено на обладнання'),
        ),
    ]
