# Generated by Django 4.1.6 on 2023-02-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nguhub', '0001_initial'),
        ('elements', '0010_element_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nguhub.location', verbose_name='Місце закріплення'),
        ),
    ]
