# Generated by Django 4.1.6 on 2023-03-05 12:44

from django.db import migrations, models
import elements.models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0015_historicalstatus_historicalelement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='photo',
            field=models.ImageField(blank=True, upload_to=elements.models.Element.directory_path, verbose_name='Фотографія'),
        ),
    ]
