# Generated by Django 4.1.6 on 2023-03-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0016_alter_element_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='historicalstatus',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
        migrations.AddField(
            model_name='status',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Додаткові коментарі'),
        ),
    ]
