# Generated by Django 4.1.6 on 2023-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0017_category_notes_historicalcategory_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Внутрішній номер'),
        ),
    ]
