# Generated by Django 4.1.6 on 2023-03-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0018_element_internalnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість'),
        ),
        migrations.AddField(
            model_name='element',
            name='inventoryNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='element',
            name='unit',
            field=models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання'),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Первісна вартість'),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='inventoryNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='historicalelement',
            name='unit',
            field=models.CharField(default='шт.', max_length=50, verbose_name='Одиниця вимірювання'),
        ),
        migrations.AlterField(
            model_name='element',
            name='employee_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача'),
        ),
        migrations.AlterField(
            model_name='element',
            name='fixed_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального'),
        ),
        migrations.AlterField(
            model_name='element',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='element',
            name='responsible_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального'),
        ),
        migrations.AlterField(
            model_name='element',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.CharField(default='1', max_length=50, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='employee_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення користувача'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='fixed_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення відповідального'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='internalNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Внутрішній номер'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='name',
            field=models.CharField(max_length=2048, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='responsible_reason',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Підстава закріплення матеріально відповідального'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Серійний номер'),
        ),
        migrations.AlterField(
            model_name='historicalelement',
            name='value',
            field=models.CharField(default='1', max_length=50, verbose_name='Кількість'),
        ),
    ]
